### ISSUE TITLE
Build - where is ../../org.globaltester.parent/org.globaltester.parent/ ?

### ISSUE THREAD

**Issue by paulvi** [PersoSim/de.persosim.simulator#91]
where is ../../org.globaltester.parent/org.globaltester.parent/ ?

It is referenced in `/de.persosim.simulator/de.persosim.simulator.ui/pom.xml`

The closest I can find is https://github.com/GlobalTester/org.globaltester.base 
but this already makes build non trivial.

Please update README with build instructions.

**Comment by markuskreusch** [comment]
It seems more details can be found in https://github.com/PersoSim/PersoSim/blob/master/setup.md and the referenced documents. The parent is in https://github.com/GlobalTester/org.globaltester.parent/tree/master/org.globaltester.parent. Will try building it and report if any problems occur.

But a note already: Throughout all the code references to local directories instead of a maven repo is used. This is a bad idea. Why didn't you use maven central or another repo to publish the necessary artifacts so that building is less cumbersome?

**Comment by hfunke** [comment]
You are right. We will update the build instructions. Currently you can find scripts to build PersoSim in org.globaltester.dev
